"""Feed instance lifecycle: create, list, status, pause/resume, run, delete.

Everything a feed needs is derived from its spec at create time:

  data dir     <data_root>/{spec.yaml,instance.json,config.json,queue.json,seen.db,briefs/}
  engine       one shared copy of engine.py in the harness scripts dir
  shims        tiny generated per-instance scripts that point the engine at
               this instance's config (the scheduler's --script mechanism has
               no argument passing, so the shim IS the argument)
  cron jobs    "[feeds:<name>] <stage>" jobs, agent jobs pinned to the spec's
               provider/model so global config drift can never skip them
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time

from . import hermes_cron as hc
from . import template
from .spec import FeedSpec

ENGINE_BASENAME = "colony-feed-engine.py"
JOB_PREFIX = "[feeds:{name}]"


def _prefix(name: str) -> str:
    return JOB_PREFIX.format(name=name)


def _instance_path(name: str) -> str:
    return os.path.expanduser(f"~/.hermes/data/feeds/{name}/instance.json")


def _load_instance(name: str) -> dict:
    try:
        with open(_instance_path(name), encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        raise SystemExit(f"no feed instance named {name!r} (see: colony feeds list)")


def _engine_src() -> str:
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "engine.py")


def _install_engine() -> str:
    dst = os.path.join(hc.scripts_dir(), ENGINE_BASENAME)
    os.makedirs(hc.scripts_dir(), exist_ok=True)
    shutil.copy2(_engine_src(), dst)
    return dst


def _write_shim(name: str, stage: str, config_path: str) -> str:
    shim = os.path.join(hc.scripts_dir(), f"feeds-{name}-{stage}.py")
    with open(shim, "w", encoding="utf-8") as f:
        f.write(f'''#!/usr/bin/env python3
# Auto-generated by `colony feeds` for instance {name!r} — do not edit.
import os, runpy
os.environ.setdefault("COLONY_FEED_CONFIG", {config_path!r})
os.environ.setdefault("COLONY_FEED_STAGE", {stage!r})
runpy.run_path(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            {ENGINE_BASENAME!r}), run_name="__main__")
''')
    return shim


# --------------------------------------------------------------------- create
def create(spec_path: str, dry_run: bool = False) -> dict:
    spec = FeedSpec.load(spec_path)
    root = spec.data_root()
    if os.path.exists(_instance_path(spec.name)):
        raise SystemExit(f"feed {spec.name!r} already exists — delete it first or pick a new name")

    prompts = {"distill": template.render_distill(spec)}
    if spec.cadence.get("digest"):
        prompts["digest"] = template.render_digest(spec)
    if spec.cadence.get("discovery"):
        prompts["discovery"] = template.render_discovery(spec)
    if dry_run:
        return {"name": spec.name, "root": root, "prompts": prompts}

    os.makedirs(spec.briefs_dir, exist_ok=True)
    os.makedirs(root, exist_ok=True)
    shutil.copy2(os.path.expanduser(spec_path), os.path.join(root, "spec" + os.path.splitext(spec_path)[1]))

    # Engine config: an explicit storage.config_path means an external
    # (possibly hand-maintained / mutated-by-other-tools) config owns the
    # collector; otherwise render one from the spec.
    config_path = spec.storage.get("config_path")
    if config_path:
        config_path = os.path.expanduser(config_path)
        if not os.path.exists(config_path):
            raise SystemExit(f"storage.config_path {config_path} does not exist")
    else:
        config_path = os.path.join(root, "config.json")
        with open(config_path, "w", encoding="utf-8") as f:
            json.dump(spec.engine_config(), f, indent=2)

    _install_engine()
    shims = {"collect": _write_shim(spec.name, "collect", config_path)}
    if spec.cadence.get("alerts"):
        shims["alert"] = _write_shim(spec.name, "alert", config_path)

    deliver_agent = (spec.destination.get("deliver", "local")
                     if spec.destination.get("kind") == "deliver" else "local")
    owner_deliver = spec.destination.get("owner_deliver", deliver_agent)

    jobs: dict[str, str] = {}
    try:
        jobs["collect"] = hc.create_job(
            f"{_prefix(spec.name)} collect", spec.cadence["collect"],
            script=os.path.basename(shims["collect"]), no_agent=True)
        jobs["distill"] = hc.create_job(
            f"{_prefix(spec.name)} distill", spec.cadence["distill"],
            prompt=prompts["distill"], deliver=deliver_agent)
        if spec.cadence.get("digest"):
            jobs["digest"] = hc.create_job(
                f"{_prefix(spec.name)} digest", spec.cadence["digest"],
                prompt=prompts["digest"], deliver=deliver_agent)
        if spec.cadence.get("alerts"):
            jobs["alert"] = hc.create_job(
                f"{_prefix(spec.name)} alert", spec.cadence["alerts"],
                script=os.path.basename(shims["alert"]), no_agent=True,
                deliver=deliver_agent)
        if spec.cadence.get("discovery"):
            jobs["discovery"] = hc.create_job(
                f"{_prefix(spec.name)} discovery", spec.cadence["discovery"],
                prompt=prompts["discovery"], deliver=owner_deliver)
    except Exception:
        for jid in jobs.values():  # roll back partial registration
            try:
                hc.remove_job(jid)
            except Exception:
                pass
        raise

    agent_jobs = [jid for stage, jid in jobs.items()
                  if stage in ("distill", "digest", "discovery")]
    hc.pin_model(agent_jobs, spec.llm.get("provider", ""), spec.llm.get("model", ""))

    instance = {"name": spec.name, "title": spec.title, "created_at": int(time.time()),
                "spec_path": os.path.abspath(os.path.expanduser(spec_path)),
                "config_path": config_path, "jobs": jobs, "shims": shims,
                "paused": False}
    with open(_instance_path(spec.name), "w", encoding="utf-8") as f:
        json.dump(instance, f, indent=2)
    return instance


# ----------------------------------------------------------------- lifecycle
def list_instances() -> list[dict]:
    base = os.path.expanduser("~/.hermes/data/feeds")
    out = []
    if not os.path.isdir(base):
        return out
    for name in sorted(os.listdir(base)):
        p = _instance_path(name)
        if os.path.exists(p):
            with open(p, encoding="utf-8") as f:
                out.append(json.load(f))
    return out


def status(name: str) -> dict:
    inst = _load_instance(name)
    spec = FeedSpec.load(inst["spec_path"]) if os.path.exists(inst["spec_path"]) else None
    info = dict(inst)
    if spec and os.path.exists(spec.queue_path):
        with open(spec.queue_path, encoding="utf-8") as f:
            q = json.load(f)
        info["queue"] = {"collected_at": q.get("collected_at"),
                         "total_items": q.get("total_items")}
    if spec and os.path.isdir(spec.briefs_dir):
        briefs = sorted(os.listdir(spec.briefs_dir))
        info["latest_brief"] = briefs[-1] if briefs else None
    live = {j["id"]: j for j in hc.find_jobs(_prefix(name))}
    info["jobs_live"] = {stage: (jid in live) for stage, jid in inst["jobs"].items()}
    return info


def pause(name: str) -> None:
    inst = _load_instance(name)
    for jid in inst["jobs"].values():
        hc.pause_job(jid)
    inst["paused"] = True
    with open(_instance_path(name), "w", encoding="utf-8") as f:
        json.dump(inst, f, indent=2)


def resume(name: str) -> None:
    inst = _load_instance(name)
    for jid in inst["jobs"].values():
        hc.resume_job(jid)
    inst["paused"] = False
    with open(_instance_path(name), "w", encoding="utf-8") as f:
        json.dump(inst, f, indent=2)


def run(name: str, stage: str) -> None:
    """Run one stage now. collect/alert run synchronously (output streams);
    agent stages are triggered detached because they can run for minutes."""
    inst = _load_instance(name)
    if stage in ("collect", "alert"):
        shim = inst["shims"].get(stage) or inst["shims"]["collect"]
        env = dict(os.environ, COLONY_FEED_STAGE=stage)
        subprocess.run([sys.executable, shim], env=env, check=True)
        return
    jid = inst["jobs"].get(stage)
    if not jid:
        raise SystemExit(f"feed {name!r} has no {stage!r} job")
    hc.run_job_detached(jid)
    print(f"triggered {stage} (job {jid}) — check the scheduler's output dir for results")


def delete(name: str, purge: bool = False) -> None:
    inst = _load_instance(name)
    for jid in inst["jobs"].values():
        try:
            hc.remove_job(jid)
        except Exception as e:
            print(f"warning: could not remove job {jid}: {e}", file=sys.stderr)
    for shim in inst.get("shims", {}).values():
        try:
            os.remove(shim)
        except FileNotFoundError:
            pass
    if purge:
        shutil.rmtree(os.path.dirname(_instance_path(name)), ignore_errors=True)
    else:
        os.remove(_instance_path(name))
