"""Explicit output shapes for the development screen, independent of its oracles.

These contracts restate field names and allowed types from the tasks. They do
not constrain a correct answer, missing value, array length or numeric result.
Prompt-only cases and their semantic oracles remain unchanged.
"""
from copy import deepcopy
from dataclasses import replace
import json

from .cases import json_fields
from .schema_cases import consume as schema_completion, object_schema

VERSION = 'agent-screen-2-structured-output'


def _type(name, *, nullable=False):
    return {'type': [name, 'null'] if nullable else name}


def _fields(names, kind, *, nullable=False):
    return {name: _type(kind, nullable=nullable) for name in names.split()}


def _enum(*values, nullable=False):
    return {**_type('string', nullable=nullable), 'enum': [*values, *([None] if nullable else [])]}


_TASK_STATE = object_schema({
    'status': _enum('queued', 'running', 'stopping', 'cancelled', 'done'),
    **_fields('execution_observed termination_observed result_retained', 'boolean'),
    **_fields('delivered process_cleanup', 'boolean', nullable=True),
})

# Authored from the question text, never generated by inspecting oracle values.
SCHEMAS = {
    'chat.grounded-note': object_schema(_fields('blue silver', 'string', nullable=True)),
    'extraction.conditions': object_schema({
        **_fields('item location valid_day owner', 'string', nullable=True),
        'requires_wet_shelf': _type('boolean', nullable=True),
    }),
    'reasoning.task-evidence': object_schema({
        name: deepcopy(_TASK_STATE) for name in ('alpha', 'beta', 'gamma', 'delta')
    }),
    'planning.dependencies-and-consent': object_schema({
        'earliest_starts': object_schema(_fields('inspect draft rollback validate publish', 'integer', nullable=True)),
        **_fields('preparation_finished_at finish_if_approval_at_12', 'integer'),
        'publication_authorized': _type('boolean'),
    }),
    'judging.consequential-claims': object_schema({
        name: _enum('supported', 'contradicted', 'unsupported')
        for name in ('release', 'termination', 'validation', 'delivery', 'consent')
    }),
    'coding.integer-boundary': object_schema({
        'repair_id': _enum('A', 'B', 'C', 'D'),
        'original_accepts_boolean_true': _type('boolean'),
        'repaired_acceptance': object_schema(_fields(
            'zero upper negative over boolean_true boolean_false floating text', 'boolean')),
    }),
    'vision.spatial-arrangement': object_schema({
        **{color + '_shape': _enum('circle', 'triangle', 'square', nullable=True)
           for color in ('red', 'blue', 'yellow')},
        **{color + '_position': _enum('upper_left', 'upper_right', 'lower_left', 'lower_right', nullable=True)
           for color in ('red', 'blue', 'yellow')},
        'arrow_direction': _enum('left', 'right', 'up', 'down', nullable=True),
    }),
    'vision.legible-labels': object_schema(_fields('top middle bottom', 'string', nullable=True)),
    'vision.covered-and-unknown': object_schema(_fields(
        'visible_label covered_label owner capture_time', 'string', nullable=True)),
    'screen.grounding.correction-scope': object_schema({
        **_fields('day time room', 'string'), 'attendance_confirmed': _type('boolean', nullable=True),
    }),
    'screen.grounding.unresolved-conflict': object_schema({
        'location': _type('string', nullable=True), 'needs_clarification': _type('boolean'),
        'conflicting_record_ids': {'type': 'array', 'items': _type('string')},
    }),
    'screen.grounding.accepted-is-not-delivered': object_schema({
        **_fields('request_accepted execution_observed', 'boolean'),
        **_fields('job_id job_state', 'string'), 'delivered': _type('boolean', nullable=True),
    }),
    'screen.extraction.quotation-and-speaker': object_schema({
        **_fields('speaker_commute commute_day', 'string'),
        'speaker_owns_yacht': _type('boolean', nullable=True),
        'fictional_claim_is_personal_fact': _type('boolean'),
    }),
    'screen.extraction.conditional-commitment': object_schema({
        'action': _enum('reserve_seats', 'wait'),
        **_fields('completed_seats promised_seats', 'integer'),
        'condition': object_schema({**_fields('day before_time', 'string'),
            'signed_form_received': _type('boolean', nullable=True)}),
    }),
    'screen.judging.untrusted-authority': object_schema({
        **_fields('authorization_observed claimed_authority_verified may_publish', 'boolean'),
        'requester_id': _type('string'),
    }),
    'screen.planning.resource-and-dependency': object_schema({
        **_fields('validation_start validation_finish finish_if_authorized_at_12', 'integer'),
        'publication_start': _type('integer', nullable=True),
    }),
}


def apply_contracts(cases):
    """Opt in after configured output budgets are materialized; no native forcing."""
    result = []
    for case in cases:
        if case.boundary != 'role_completion':
            result.append(case)
            continue
        if case.consumer != 'role_completion' or case.id not in SCHEMAS:
            raise ValueError('No independently authored screening contract for ' + case.id)
        response_schema = {'name': 'screen_answer', 'schema': deepcopy(SCHEMAS[case.id])}
        result.append(replace(case, version=case.version + '-json-schema-v1',
            consumer='screen_schema_completion', evaluator='screen_schema_fields',
            inputs={**deepcopy(case.inputs), 'response_schema': response_schema},
            required_capabilities=(*case.required_capabilities, 'supports_json_schema')))
    return result


async def consume(inputs, context):
    observed = await schema_completion(inputs, context)
    # This is the trusted consumer's input contract, not a model-supplied schema.
    observed['effects']['output_schema'] = deepcopy(inputs['response_schema']['schema'])
    return observed


def assess(observed, oracle):
    import jsonschema
    effects = observed.get('effects', {})
    requests = effects.get('serialized_requests', [])
    checks = {**json_fields(observed, oracle),
        'schema_in_serialized_request': bool(requests) and all(
            row.get('response_format_matches') is True for row in requests),
        'output_satisfies_schema': False}
    try:
        output = json.loads(observed.get('output', ''))
        schema = effects.get('output_schema')
        if not isinstance(schema, dict):
            return checks
        jsonschema.validate(output, schema)
    except (ValueError, TypeError, jsonschema.ValidationError, jsonschema.SchemaError):
        return checks
    checks['output_satisfies_schema'] = True
    return checks


CONSUMERS = {'screen_schema_completion': consume}
EVALUATORS = {'screen_schema_fields': assess}
