"""Colony setup wizard - ``colony init``.

Guides the user through first-time configuration:
1. Check dependencies
2. Host detection (OpenClaw, etc.)
3. Neo4j setup (auto-start via Docker or manual)
4. Write .env
5. Database migrations
6. Verify connectivity + print capability status
7. Print next steps
"""

from __future__ import annotations

import asyncio
import os
import secrets
import shutil
import socket
import subprocess
import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ImportError:
        tomllib = None  # type: ignore[assignment]


# ── ANSI helpers ────────────────────────────────────────────────────────────

def _green(msg: str) -> str:
    return f"\033[92m{msg}\033[0m"

def _red(msg: str) -> str:
    return f"\033[91m{msg}\033[0m"

def _yellow(msg: str) -> str:
    return f"\033[93m{msg}\033[0m"

def _bold(msg: str) -> str:
    return f"\033[1m{msg}\033[0m"

def _prompt(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"{prompt}{suffix}: ").strip()
    return val or default


# ── Check helpers ───────────────────────────────────────────────────────────

def _check_command(cmd: str) -> bool:
    return shutil.which(cmd) is not None

def _check_python() -> tuple[bool, str]:
    version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    ok = sys.version_info >= (3, 11)
    return ok, version

def _check_neo4j() -> tuple[bool, str]:
    """Check if Neo4j is reachable on the default bolt port."""
    try:
        with socket.create_connection(("localhost", 7687), timeout=2):
            return True, "localhost:7687"
    except (ConnectionRefusedError, OSError):
        return False, "not reachable"

def _check_port(port: int) -> bool:
    try:
        with socket.create_connection(("localhost", port), timeout=1):
            return True
    except (ConnectionRefusedError, OSError):
        return False

def _check_docker() -> bool:
    """Check if Docker is available and the daemon is running."""
    if not shutil.which("docker"):
        return False
    try:
        result = subprocess.run(
            ["docker", "info"], capture_output=True, timeout=5,
        )
        return result.returncode == 0
    except Exception:
        return False

def _wait_for_neo4j(timeout: int = 60) -> bool:
    """Wait for Neo4j to become reachable on bolt port."""
    import time
    start = time.time()
    while time.time() - start < timeout:
        ok, _ = _check_neo4j()
        if ok:
            return True
        time.sleep(2)
    return False

def _start_neo4j_docker() -> bool:
    """Start Neo4j via docker compose. Returns True if successful."""
    compose_path = Path(__file__).resolve().parents[2] / "docker-compose.yml"
    if not compose_path.exists():
        # Try relative to cwd
        compose_path = Path("docker-compose.yml")
    if not compose_path.exists():
        return False

    try:
        result = subprocess.run(
            ["docker", "compose", "-f", str(compose_path), "up", "-d", "neo4j"],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode != 0:
            print(f"    ⚠️ docker compose failed: {result.stderr.strip()}")
            return False
        return True
    except Exception as exc:
        print(f"    ⚠️ docker compose failed: {exc}")
        return False


# ── .env helpers ────────────────────────────────────────────────────────────

def _write_env(env_path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Colony Sidecar Configuration",
        "# Generated by 'colony init'",
        "#",
        "# Colony is a sidecar — it gets LLM credentials from its host",
        "# (OpenClaw, Hermes, etc.) at runtime via POST /v1/host/configure.",
        "# You do NOT need to configure LLM keys here.",
        "",
    ]
    for key, val in values.items():
        lines.append(f"{key}={val}")
    env_path.write_text("\n".join(lines) + "\n")

def _load_existing_env(env_path: Path) -> dict[str, str]:
    if not env_path.exists():
        return {}
    env: dict[str, str] = {}
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    return env


# ── Main wizard ─────────────────────────────────────────────────────────────

def run_init(root_dir: str | None = None) -> int:
    """Run the interactive setup wizard. Returns exit code."""
    base = Path(root_dir) if root_dir else Path(".")
    env_path = base / ".env"

    print()
    print(_bold("🔧 Colony Sidecar Setup Wizard"))
    print(_bold("=" * 40))
    print()

    # ── Step 1: Dependency checks ───────────────────────────────────────

    print(_bold("Step 1: Dependency checks"))
    print()

    py_ok, py_ver = _check_python()
    print(f"  Python: {py_ver} {'✅' if py_ok else '❌ (need 3.11+)'}")

    critical_deps = ["fastapi", "uvicorn", "pydantic"]
    optional_deps = ["neo4j", "litellm"]
    for dep in critical_deps:
        try:
            __import__(dep)
            print(f"  {dep}: ✅")
        except ImportError:
            print(f"  {dep}: ❌ (run: pip install {dep})")
    for dep in optional_deps:
        try:
            __import__(dep)
            print(f"  {dep}: ✅ (optional)")
        except ImportError:
            print(f"  {dep}: ⚪ not installed (optional)")

    docker_ok = _check_docker()
    print(f"  Docker: {'✅ available' if docker_ok else '⚪ not available'}")

    port = 7777
    port_taken = _check_port(port)
    print(f"  Port {port}: {'⚠️ in use' if port_taken else '✅ available'}")

    if not py_ok:
        print(_red("\nPython 3.11+ required. Please upgrade and re-run."))
        return 1

    print()

    # ── Step 2: Host detection ──────────────────────────────────────────

    print(_bold("Step 2: Host framework"))
    print()
    print("  Colony is a sidecar — it needs a host (OpenClaw, Hermes, etc.)")
    print("  to provide LLM credentials at runtime.")
    print()

    host_choice = _prompt("  Which host framework? [openclaw/other]", "openclaw")

    if host_choice.lower() in ("openclaw", "oc", ""):
        # Detect OpenClaw config
        oc_config_path = Path.home() / ".openclaw" / "openclaw.json"
        if oc_config_path.exists():
            print(f"  ✅ OpenClaw config found: {oc_config_path}")
            print("  Colony will receive LLM credentials automatically when")
            print("  the OpenClaw plugin connects on startup.")
        else:
            print("  ⚠️ No OpenClaw config found at ~/.openclaw/openclaw.json")
            print("  Make sure OpenClaw is configured before starting Colony.")
    else:
        print("  Colony will receive LLM credentials from your host on connect.")

    print()

    # ── Step 3: Neo4j setup ─────────────────────────────────────────────

    print(_bold("Step 3: Neo4j graph memory"))
    print()

    neo4j_ok, neo4j_info = _check_neo4j()

    if neo4j_ok:
        print(f"  ✅ Neo4j is already running ({neo4j_info})")
        neo4j_password = _prompt("  Neo4j password", "")
    elif docker_ok:
        print("  Neo4j is required for graph memory (persistent knowledge,")
        print("  connections, world model).")
        print()
        start_neo4j = _prompt("  Start Neo4j via Docker? [Y/n]", "Y")
        if start_neo4j.lower() in ("y", "yes", ""):
            neo4j_password = secrets.token_urlsafe(16)
            print("  Starting Neo4j...")
            if _start_neo4j_docker():
                print("  Waiting for Neo4j to become ready...")
                if _wait_for_neo4j():
                    print(f"  ✅ Neo4j started (bolt://localhost:7687)")
                    print(f"  Generated password: {neo4j_password}")
                else:
                    print("  ⚠️ Neo4j started but not reachable yet (may need a moment)")
                    neo4j_password = _prompt("  Neo4j password", "colony12345")
            else:
                print("  ❌ Failed to start Neo4j via Docker")
                neo4j_password = _prompt("  Enter Neo4j password (or leave blank to skip)", "")
        else:
            neo4j_password = _prompt("  Enter Neo4j connection details (password, or blank to skip)", "")
    else:
        print("  Neo4j is required for graph memory but Docker is not available.")
        print("  Install Docker (https://docs.docker.com/get-docker/) or set up")
        print("  Neo4j manually (https://neo4j.com/download/).")
        print()
        neo4j_password = _prompt("  Neo4j password (or leave blank to skip — memory will be degraded)", "")

    print()

    # ── Step 4: Write .env ──────────────────────────────────────────────

    print(_bold("Step 4: Writing configuration"))
    print()

    existing = _load_existing_env(env_path)
    values: dict[str, str] = {
        "COLONY_SIDECAR_PORT": existing.get("COLONY_SIDECAR_PORT", "7777"),
        "COLONY_SIDECAR_HOST": existing.get("COLONY_SIDECAR_HOST", "127.0.0.1"),
        "NEO4J_URI": existing.get("NEO4J_URI", "bolt://localhost:7687"),
        "NEO4J_USER": existing.get("NEO4J_USER", "neo4j"),
        "NEO4J_PASSWORD": neo4j_password or existing.get("NEO4J_PASSWORD", ""),
        "COLONY_API_KEY": existing.get("COLONY_API_KEY", secrets.token_urlsafe(32)),
        "COLONY_CONTACTS_DB": existing.get("COLONY_CONTACTS_DB", "colony-contacts.db"),
        "LOG_LEVEL": existing.get("LOG_LEVEL", "info"),
    }

    _write_env(env_path, values)
    print(f"  ✅ Written to {env_path}")

    print()

    # ── Step 5: Database setup ──────────────────────────────────────────

    print(_bold("Step 5: Database setup"))
    print()

    # Contacts DB
    contacts_db = base / values.get("COLONY_CONTACTS_DB", "colony-contacts.db")
    try:
        from colony_sidecar.contacts.store import SQLiteContactStore
        store = SQLiteContactStore(db_path=str(contacts_db))
        print(f"  ✅ Contacts DB initialized ({contacts_db})")
    except Exception as exc:
        print(f"  ⚠️ Contacts DB init failed: {exc}")

    # Goals DB
    try:
        from colony_sidecar.goals.store import GoalStore
        goals_db = base / "colony-goals.db"
        gs = GoalStore(db_path=str(goals_db))
        print(f"  ✅ Goals DB initialized ({goals_db})")
    except Exception as exc:
        print(f"  ⚠️ Goals DB init failed: {exc}")

    # Neo4j connectivity test
    if neo4j_password:
        try:
            from colony_sidecar.intelligence.graph.client import ColonyGraph, GraphConfig
            from pydantic import SecretStr

            async def _test_neo4j():
                config = GraphConfig(
                    uri=values["NEO4J_URI"],
                    auth=(values["NEO4J_USER"], SecretStr(neo4j_password)),
                )
                graph = ColonyGraph(config=config)
                try:
                    await graph.health_check()
                    print(f"  ✅ Neo4j connected ({values['NEO4J_URI']})")
                finally:
                    await graph.close()

            asyncio.run(_test_neo4j())
        except Exception as exc:
            print(f"  ⚠️ Neo4j connection failed: {exc}")
    else:
        print("  ⚪ Neo4j skipped (no password — memory will be degraded)")

    print()

    # ── Step 6: Self-knowledge seeding ──────────────────────────────────

    print(_bold("Step 6: Self-knowledge seeding"))
    print()
    print("  Seeding Colony with understanding of itself...")
    print()

    # Seed world model entities (SQLite)
    try:
        from colony_sidecar.world_model.store import WorldModelStore
        from colony_sidecar.seed import WORLD_MODEL_ENTITIES
        from colony_sidecar.world_model.entities import BaseEntity

        world_db = base / "colony-world.db"

        async def seed_entities():
            world_store = WorldModelStore(db_path=str(world_db))
            count = 0
            for entity in WORLD_MODEL_ENTITIES:
                e = BaseEntity(
                    name=entity["name"],
                    type=entity["type"],
                    attributes=entity.get("attributes", {}),
                )
                await world_store.upsert_entity(e)
                count += 1
            return count

        count = asyncio.run(seed_entities())
        print(f"  ✅ World model seeded ({count} entities)")
    except Exception as exc:
        print(f"  ⚠️ World model seed failed: {exc}")

    if neo4j_password:
        print("  ⚪ Neo4j graph seeding deferred (runs on first start)")
    else:
        print("  ⚪ Memory seeding skipped (Neo4j not configured)")

    print()

    # ── Step 7: Summary ─────────────────────────────────────────────────

    print(_bold("Step 7: Setup complete!"))
    print()

    # Capability status
    print("  Capability status:")
    print(f"    {'✅' if True else '⚪'} Safety (ResponseGate)")
    print(f"    {'✅' if True else '⚪'} Reasoning (from host at runtime)")
    print(f"    {'✅' if neo4j_password else '⚪'} Memory (ColonyGraph{' — Neo4j connected' if neo4j_password else ' — Neo4j not configured'})")
    print(f"    {'✅' if True else '⚪'} Goals")
    print(f"    {'✅' if True else '⚪'} Contacts")
    print(f"    {'✅' if True else '⚪'} World Model")
    print()

    print("  Start the sidecar:")
    print(f"    {_green('colony start')}")
    print()
    print("  Check health:")
    print(f"    {_green('colony status')}")
    print()
    print("  Your API key:")
    print(f"    {values['COLONY_API_KEY']}")
    print()
    print("  Plugin config (add to your OpenClaw config):")
    print('    {')
    print(f'      "sidecarUrl": "http://{values["COLONY_SIDECAR_HOST"]}:{values["COLONY_SIDECAR_PORT"]}",')
    print(f'      "apiKey": "{values["COLONY_API_KEY"]}"')
    print('    }')
    print()

    if not neo4j_password:
        print(_yellow("  ⚠️ Graph memory is degraded (no Neo4j)."))
        print("  To fix: install Docker and re-run 'colony init'")
        print()

    return 0
