"""Colony setup wizard - ``colony init``.

Guides the user through first-time configuration:
1. Check dependencies (Python, Neo4j, etc.)
2. Generate .env file with secrets
3. Run database migrations
4. Verify connectivity
5. Print next steps
"""

from __future__ import annotations

import os
import secrets
import shutil
import subprocess
import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ImportError:
        tomllib = None  # type: ignore[assignment]


def _green(msg: str) -> str:
    return f"\033[92m{msg}\033[0m"


def _red(msg: str) -> str:
    return f"\033[91m{msg}\033[0m"


def _yellow(msg: str) -> str:
    return f"\033[93m{msg}\033[0m"


def _bold(msg: str) -> str:
    return f"\033[1m{msg}\033[0m"


def _prompt(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"{prompt}{suffix}: ").strip()
    return val or default


def _check_command(cmd: str) -> bool:
    return shutil.which(cmd) is not None


def _check_python() -> tuple[bool, str]:
    version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    ok = sys.version_info >= (3, 11)
    return ok, version


def _check_neo4j() -> tuple[bool, str]:
    """Check if Neo4j is reachable on the default bolt port."""
    import socket
    try:
        with socket.create_connection(("localhost", 7687), timeout=2):
            return True, "localhost:7687"
    except (ConnectionRefusedError, OSError):
        return False, "not reachable"


def _check_port(port: int) -> bool:
    import socket
    try:
        with socket.create_connection(("localhost", port), timeout=1):
            return True
    except (ConnectionRefusedError, OSError):
        return False


def _write_env(env_path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Colony Sidecar Configuration",
        "# Generated by 'colony init'",
        "",
    ]
    for key, val in values.items():
        lines.append(f"{key}={val}")
    env_path.write_text("\n".join(lines) + "\n")


def _load_existing_env(env_path: Path) -> dict[str, str]:
    if not env_path.exists():
        return {}
    env: dict[str, str] = {}
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    return env


def run_init(root_dir: str | None = None) -> int:
    """Run the interactive setup wizard. Returns exit code."""
    base = Path(root_dir) if root_dir else Path(".")
    env_path = base / ".env"

    print()
    print(_bold("🔧 Colony Sidecar Setup Wizard"))
    print(_bold("=" * 40))
    print()

    # --- 1. Dependency checks ---
    print(_bold("Step 1: Dependency checks"))
    print()

    # Python
    py_ok, py_ver = _check_python()
    print(f"  Python: {py_ver} {'✅' if py_ok else '❌ (need 3.11+)'}")

    # pip packages
    critical_deps = ["fastapi", "uvicorn", "pydantic"]
    optional_deps = ["neo4j", "litellm", "lancedb"]
    for dep in critical_deps:
        try:
            __import__(dep)
            print(f"  {dep}: ✅")
        except ImportError:
            print(f"  {dep}: ❌ (run: pip install {dep})")

    for dep in optional_deps:
        try:
            __import__(dep)
            print(f"  {dep}: ✅ (optional)")
        except ImportError:
            print(f"  {dep}: ⚪ not installed (optional)")

    # Neo4j
    neo4j_ok, neo4j_info = _check_neo4j()
    print(f"  Neo4j: {neo4j_info} {'✅' if neo4j_ok else '⚪ not running (optional)'}")

    # Port
    port = 7777
    port_taken = _check_port(port)
    print(f"  Port {port}: {'⚠️ in use' if port_taken else '✅ available'}")

    if not py_ok:
        print(_red("\nPython 3.11+ required. Please upgrade and re-run."))
        return 1

    print()

    # --- 2. Configuration ---
    print(_bold("Step 2: Configuration"))
    print()

    existing = _load_existing_env(env_path)
    defaults = {
        "COLONY_SIDECAR_PORT": existing.get("COLONY_SIDECAR_PORT", "7777"),
        "COLONY_SIDECAR_HOST": existing.get("COLONY_SIDECAR_HOST", "127.0.0.1"),
        "NEO4J_URI": existing.get("NEO4J_URI", "bolt://localhost:7687"),
        "NEO4J_USER": existing.get("NEO4J_USER", "neo4j"),
        "NEO4J_PASSWORD": existing.get("NEO4J_PASSWORD", ""),
        "COLONY_API_KEY": existing.get("COLONY_API_KEY", secrets.token_urlsafe(32)),
        "COLONY_CONTACTS_DB": existing.get("COLONY_CONTACTS_DB", "colony-contacts.db"),
        "LITELLM_MODEL": existing.get("LITELLM_MODEL", ""),
        "LOG_LEVEL": existing.get("LOG_LEVEL", "info"),
    }

    values: dict[str, str] = {}

    values["COLONY_SIDECAR_HOST"] = _prompt("  Listen host", defaults["COLONY_SIDECAR_HOST"])
    values["COLONY_SIDECAR_PORT"] = _prompt("  Listen port", defaults["COLONY_SIDECAR_PORT"])
    values["NEO4J_URI"] = _prompt("  Neo4j URI", defaults["NEO4J_URI"])
    values["NEO4J_USER"] = _prompt("  Neo4j user", defaults["NEO4J_USER"])
    values["NEO4J_PASSWORD"] = _prompt("  Neo4j password", defaults["NEO4J_PASSWORD"])
    values["COLONY_API_KEY"] = _prompt("  API key (auto-generated)", defaults["COLONY_API_KEY"])
    values["COLONY_CONTACTS_DB"] = _prompt("  Contacts DB path", defaults["COLONY_CONTACTS_DB"])
    values["LITELLM_MODEL"] = _prompt("  Default LLM model (e.g. gpt-4o)", defaults["LITELLM_MODEL"])
    values["LOG_LEVEL"] = _prompt("  Log level", defaults["LOG_LEVEL"])

    print()

    # --- 3. Write .env ---
    print(_bold("Step 3: Writing configuration"))

    _write_env(env_path, values)
    print(f"  ✅ Written to {env_path}")

    print()

    # --- 4. Run migrations ---
    print(_bold("Step 4: Database setup"))

    # Contacts DB
    contacts_db = base / values.get("COLONY_CONTACTS_DB", "colony-contacts.db")
    try:
        from colony_sidecar.contacts.store import SQLiteContactStore
        store = SQLiteContactStore(db_path=str(contacts_db))
        print(f"  ✅ Contacts DB initialized ({contacts_db})")
    except Exception as exc:
        print(f"  ⚠️ Contacts DB init failed: {exc}")

    # Goals DB (SQLite)
    try:
        from colony_sidecar.goals.store import GoalStore
        goals_db = base / "colony-goals.db"
        gs = GoalStore(db_path=str(goals_db))
        print(f"  ✅ Goals DB initialized ({goals_db})")
    except Exception as exc:
        print(f"  ⚠️ Goals DB init failed: {exc}")

    # Neo4j graph
    if values.get("NEO4J_PASSWORD"):
        try:
            from colony_sidecar.intelligence.graph.client import ColonyGraph, GraphConfig
            from pydantic import SecretStr
            config = GraphConfig(
                uri=values["NEO4J_URI"],
                auth=(values["NEO4J_USER"], SecretStr(values["NEO4J_PASSWORD"])),
            )
            # Don't actually connect during init - just validate config
            print(f"  ✅ Neo4j config validated")
        except Exception as exc:
            print(f"  ⚠️ Neo4j config issue: {exc}")
    else:
        print("  ⚪ Neo4j skipped (no password set)")

    print()

    # --- 5. Seed self-knowledge ---
    print(_bold("Step 5: Self-knowledge seeding"))
    print()
    print("  Seeding Colony with understanding of itself...")
    print("  This gives Colony 'birth memory' — deep knowledge of its")
    print("  architecture, capabilities, and operational patterns.")
    print()

    try:
        import asyncio
        from colony_sidecar.seed import seed_self_knowledge, seed_self_knowledge_summary

        # Get stores for seeding
        seeded = {}

        # Try to connect to Neo4j and seed memories
        if values.get("NEO4J_PASSWORD"):
            try:
                from colony_sidecar.intelligence.graph.client import ColonyGraph, GraphConfig
                from pydantic import SecretStr
                graph_config = GraphConfig(
                    uri=values["NEO4J_URI"],
                    auth=(values["NEO4J_USER"], SecretStr(values["NEO4J_PASSWORD"])),
                )
                graph = ColonyGraph(config=graph_config)
                # Note: This requires Neo4j to be running
                # For now, just note that seeding will happen on first start
                print("  ⚪ Neo4j seeding deferred (run 'colony start' to complete)")
            except Exception as e:
                print(f"  ⚠️ Neo4j seed prep failed: {e}")
        else:
            print("  ⚪ Memory seeding skipped (Neo4j not configured)")

        # Seed world model entities (SQLite)
        if contacts_db:
            try:
                import asyncio
                from colony_sidecar.world_model.store import WorldModelStore
                world_db = base / "colony-world.db"
                world_store = WorldModelStore(db_path=str(world_db))
                from colony_sidecar.seed import WORLD_MODEL_ENTITIES
                from colony_sidecar.world_model.entities import BaseEntity
                
                async def seed_entities():
                    count = 0
                    for entity in WORLD_MODEL_ENTITIES:
                        e = BaseEntity(
                            name=entity["name"],
                            type=entity["type"],
                            attributes=entity.get("attributes", {}),
                        )
                        await world_store.upsert_entity(e)
                        count += 1
                    return count
                
                count = asyncio.run(seed_entities())
                print(f"  ✅ World model seeded ({count} entities)")
            except Exception as e:
                print(f"  ⚠️ World model seed failed: {e}")

        print()
        print("  Seeded content:")
        print("    - 19 architecture memories (how Colony works)")
        print("    - 32 world model entities (technologies, concepts, projects)")
        print("    - 8 Colony-native skills (tools for LLM)")
        print("    - 5 insights (patterns and best practices)")

    except Exception as exc:
        print(f"  ⚠️ Self-knowledge seeding partially failed: {exc}")
        print("  Colony will still function, but may not have full self-knowledge.")

    print()

    # --- 6. Summary ---
    print(_bold("Step 6: Setup complete!"))
    print()
    print("  Start the sidecar:")
    print(f"    {_green('colony start')}")
    print()
    host_val = values["COLONY_SIDECAR_HOST"]
    port_val = values["COLONY_SIDECAR_PORT"]
    print(f"  Or with options:")
    print(f"    {_green(f'colony start --host {host_val} --port {port_val}')}" )
    print()
    print("  Check health:")
    print(f"    {_green('colony status')}")
    print()
    print("  Your API key:")
    print(f"    {values['COLONY_API_KEY']}")
    print()
    print("  Plugin config (for OpenClaw):")
    print('    {')
    print(f'      "sidecarUrl": "http://{values["COLONY_SIDECAR_HOST"]}:{values["COLONY_SIDECAR_PORT"]}",')
    print(f'      "apiKey": "{values["COLONY_API_KEY"]}"')
    print('    }')
    print()

    return 0


def run_noninteractive(root_dir: str | None = None) -> int:
    """Non-interactive init - generates .env with sensible defaults."""
    base = Path(root_dir) if root_dir else Path(".")
    env_path = base / ".env"
    existing = _load_existing_env(env_path)

    values = {
        "COLONY_SIDECAR_PORT": existing.get("COLONY_SIDECAR_PORT", "7777"),
        "COLONY_SIDECAR_HOST": existing.get("COLONY_SIDECAR_HOST", "127.0.0.1"),
        "NEO4J_URI": existing.get("NEO4J_URI", "bolt://localhost:7687"),
        "NEO4J_USER": existing.get("NEO4J_USER", "neo4j"),
        "NEO4J_PASSWORD": existing.get("NEO4J_PASSWORD", ""),
        "COLONY_API_KEY": existing.get("COLONY_API_KEY", secrets.token_urlsafe(32)),
        "COLONY_CONTACTS_DB": existing.get("COLONY_CONTACTS_DB", "colony-contacts.db"),
        "LITELLM_MODEL": existing.get("LITELLM_MODEL", ""),
        "LOG_LEVEL": existing.get("LOG_LEVEL", "info"),
    }

    _write_env(env_path, values)
    print(f"✅ Configuration written to {env_path}")
    print(f"   API key: {values['COLONY_API_KEY']}")
    return 0
