/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/host/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_host_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/memory/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Read */
        post: operations["memory_read_v1_host_memory_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/memory/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Write */
        post: operations["memory_write_v1_host_memory_write_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/memory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Search */
        post: operations["memory_search_v1_host_memory_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/memory/flush": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Flush */
        post: operations["memory_flush_v1_host_memory_flush_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/memory/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Embed */
        post: operations["memory_embed_v1_host_memory_embed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/context/assemble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Context Assemble */
        post: operations["context_assemble_v1_host_context_assemble_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/reasoning/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reasoning Turn */
        post: operations["reasoning_turn_v1_host_reasoning_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/signals/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signals Ingest */
        post: operations["signals_ingest_v1_host_signals_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/turns/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turns Sync */
        post: operations["turns_sync_v1_host_turns_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/safety/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Safety Check */
        post: operations["safety_check_v1_host_safety_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ContextAssembleRequest */
        ContextAssembleRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            incoming_message: components["schemas"]["HostMessage"];
            /** Available Tools */
            available_tools?: string[] | null;
            /** Citations Mode */
            citations_mode?: ("off" | "inline" | "appendix") | null;
        };
        /** ContextAssembleResponse */
        ContextAssembleResponse: {
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["ContextSection"][];
            /** Notices */
            notices?: string[] | null;
        };
        /** ContextSection */
        ContextSection: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Body */
            body: string;
            /** Priority */
            priority?: number | null;
            /** Citations */
            citations?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostHealthResponse */
        HostHealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "starting" | "stopping";
            /**
             * Api Version
             * @default 1.0.0
             */
            api_version: string;
            /**
             * Capabilities
             * @default []
             */
            capabilities: string[];
            /** Notes */
            notes?: {
                [key: string]: string;
            } | null;
        };
        /** HostIdentity */
        HostIdentity: {
            /** Host Id */
            host_id: string;
            /** Host Version */
            host_version?: string | null;
            /** Plugin Version */
            plugin_version?: string | null;
            /** Instance Id */
            instance_id?: string | null;
        };
        /** HostMessage */
        HostMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system" | "tool";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** HostTurnContext */
        HostTurnContext: {
            /** Session Id */
            session_id: string;
            /** Contact Id */
            contact_id: string;
            /** Channel Id */
            channel_id?: string | null;
            /** Turn Id */
            turn_id?: string | null;
            /** Locale */
            locale?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** MemoryEmbedRequest */
        MemoryEmbedRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Inputs */
            inputs: string[];
            /** Model */
            model?: string | null;
        };
        /** MemoryEmbedResponse */
        MemoryEmbedResponse: {
            /** Model */
            model: string;
            /** Vectors */
            vectors: number[][];
        };
        /** MemoryEntry */
        MemoryEntry: {
            /** Id */
            id: string;
            /** Content */
            content: string;
            /** Type */
            type?: string | null;
            /** Strength */
            strength?: number | null;
            /** Person Id */
            person_id?: string | null;
            /** Entities */
            entities?: string[] | null;
            /** Tags */
            tags?: string[] | null;
            /** Created At */
            created_at?: string | null;
            /** Score */
            score?: number | null;
        };
        /** MemoryFlushRequest */
        MemoryFlushRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Reason */
            reason?: string | null;
        };
        /** MemoryFlushResponse */
        MemoryFlushResponse: {
            /** Accepted */
            accepted: boolean;
            /** Job Id */
            job_id?: string | null;
        };
        /** MemoryReadRequest */
        MemoryReadRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Memory Id */
            memory_id?: string | null;
            /** Person Id */
            person_id?: string | null;
            /** Limit */
            limit?: number | null;
        };
        /** MemoryReadResponse */
        MemoryReadResponse: {
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["MemoryEntry"][];
        };
        /** MemorySearchRequest */
        MemorySearchRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Query */
            query: string;
            /** Limit */
            limit?: number | null;
            /** Min Score */
            min_score?: number | null;
            /** Person Id */
            person_id?: string | null;
            /** Types */
            types?: string[] | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** MemorySearchResponse */
        MemorySearchResponse: {
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["MemoryEntry"][];
        };
        /** MemoryWriteRequest */
        MemoryWriteRequest: {
            identity: components["schemas"]["HostIdentity"];
            context?: components["schemas"]["HostTurnContext"] | null;
            /** Content */
            content: string;
            /** Type */
            type?: string | null;
            /** Person Id */
            person_id?: string | null;
            /** Entities */
            entities?: string[] | null;
            /** Tags */
            tags?: string[] | null;
            /** Strength */
            strength?: number | null;
        };
        /** MemoryWriteResponse */
        MemoryWriteResponse: {
            /** Id */
            id: string;
            /** Accepted */
            accepted: boolean;
        };
        /** ReasoningToolCall */
        ReasoningToolCall: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
        };
        /** ReasoningTurnRequest */
        ReasoningTurnRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            /** Messages */
            messages: components["schemas"]["HostMessage"][];
            /** Available Tools */
            available_tools?: string[];
            /** Model Override */
            model_override?: string | null;
        };
        /** ReasoningTurnResponse */
        ReasoningTurnResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "needs_tool" | "error";
            message?: components["schemas"]["HostMessage"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ReasoningToolCall"][];
            /** Usage */
            usage?: {
                [key: string]: unknown;
            };
            /** Error */
            error?: string | null;
        };
        /** SafetyCheckRequest */
        SafetyCheckRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            /** Response Text */
            response_text: string;
            /** Incoming Message Text */
            incoming_message_text?: string | null;
            /** Target Gateway */
            target_gateway?: string | null;
            /** Trust Tier */
            trust_tier?: string | null;
            /** Mentioned Entities */
            mentioned_entities?: string[] | null;
        };
        /** SafetyCheckResponse */
        SafetyCheckResponse: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "pass" | "block" | "pending";
            /** Blocked */
            blocked: boolean;
            /** Blocking Layer */
            blocking_layer?: number | null;
            /** Reason */
            reason?: string | null;
            /** Flagged Excerpt */
            flagged_excerpt?: string | null;
            /** Layer Results */
            layer_results?: {
                [key: string]: unknown;
            } | null;
        };
        /** SignalIngestRequest */
        SignalIngestRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            incoming_message?: components["schemas"]["HostMessage"] | null;
            outgoing_message?: components["schemas"]["HostMessage"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ReasoningToolCall"][];
            /** Correction */
            correction?: string | null;
        };
        /** SignalIngestResponse */
        SignalIngestResponse: {
            /** Accepted */
            accepted: boolean;
            /** Signals Recorded */
            signals_recorded: number;
        };
        /** TurnSyncRequest */
        TurnSyncRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            /** Topics */
            topics?: string[];
            /** Entities */
            entities?: string[];
            /** Pending Tasks */
            pending_tasks?: string[];
            /** Tools Used */
            tools_used?: string[];
            /** Summary */
            summary?: string | null;
        };
        /** TurnSyncResponse */
        TurnSyncResponse: {
            /** Accepted */
            accepted: boolean;
            /** Continuity Updated */
            continuity_updated: boolean;
            /** Skipped Reason */
            skipped_reason?: string | null;
            /** Errors */
            errors?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_host_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostHealthResponse"];
                };
            };
        };
    };
    memory_read_v1_host_memory_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryReadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_write_v1_host_memory_write_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_search_v1_host_memory_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemorySearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_flush_v1_host_memory_flush_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryFlushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryFlushResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_embed_v1_host_memory_embed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryEmbedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEmbedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    context_assemble_v1_host_context_assemble_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextAssembleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextAssembleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reasoning_turn_v1_host_reasoning_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasoningTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReasoningTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signals_ingest_v1_host_signals_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turns_sync_v1_host_turns_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    safety_check_v1_host_safety_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafetyCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
