/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/host/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_host_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/memory/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Read */
        post: operations["memory_read_v1_host_memory_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/memory/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Write */
        post: operations["memory_write_v1_host_memory_write_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/memory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Search */
        post: operations["memory_search_v1_host_memory_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/memory/flush": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Flush */
        post: operations["memory_flush_v1_host_memory_flush_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/memory/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Memory Embed */
        post: operations["memory_embed_v1_host_memory_embed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/context/assemble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Context Assemble */
        post: operations["context_assemble_v1_host_context_assemble_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/reasoning/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reasoning Turn */
        post: operations["reasoning_turn_v1_host_reasoning_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/signals/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signals Ingest */
        post: operations["signals_ingest_v1_host_signals_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/turns/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turns Sync */
        post: operations["turns_sync_v1_host_turns_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/safety/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Safety Check */
        post: operations["safety_check_v1_host_safety_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_v1_host_goals_get"];
        put?: never;
        /** Create Goal */
        post: operations["create_goal_v1_host_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_v1_host_goals__goal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Goal */
        patch: operations["update_goal_v1_host_goals__goal_id__patch"];
        trace?: never;
    };
    "/v1/host/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["list_contacts_v1_host_contacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contact */
        get: operations["get_contact_v1_host_contacts__contact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/contacts/{contact_id}/style": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Contact Style */
        post: operations["get_contact_style_v1_host_contacts__contact_id__style_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/briefings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Briefings */
        get: operations["list_briefings_v1_host_briefings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/world/entities/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Entities */
        post: operations["query_entities_v1_host_world_entities_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/world/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entities */
        get: operations["list_entities_v1_host_world_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/cognition/cycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cognition Cycle */
        post: operations["cognition_cycle_v1_host_cognition_cycle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/cognition/cpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cpi */
        get: operations["get_cpi_v1_host_cognition_cpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/research/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Research */
        post: operations["start_research_v1_host_research_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research */
        get: operations["list_research_v1_host_research_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/delivery/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Deliveries */
        get: operations["list_pending_deliveries_v1_host_delivery_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/delivery/mark-sent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Delivery Sent */
        post: operations["mark_delivery_sent_v1_host_delivery_mark_sent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/synthesis/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover Connections */
        post: operations["discover_connections_v1_host_synthesis_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/learning/correction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Correction */
        post: operations["submit_correction_v1_host_learning_correction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/learning/engagement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Engagement */
        post: operations["submit_engagement_v1_host_learning_engagement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/learning/weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Learning Weights */
        get: operations["get_learning_weights_v1_host_learning_weights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/skills/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_v1_host_skills_registry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/skills/registry/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill */
        get: operations["get_skill_v1_host_skills_registry__skill_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Insights */
        get: operations["list_insights_v1_host_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/insights/{insight_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Insight */
        post: operations["dismiss_insight_v1_host_insights__insight_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/context/enriched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enriched Context
         * @description Pull from all intelligence systems to build enriched context.
         *
         *     This is the one-stop endpoint for context assembly — it queries
         *     memory, relationships, goals, world model, insights, and style
         *     in parallel and returns assembled sections.
         */
        post: operations["enriched_context_v1_host_context_enriched_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/identity/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity Status */
        get: operations["identity_status_v1_host_identity_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/identity/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Identity Init */
        post: operations["identity_init_v1_host_identity_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/chain/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chain Verify */
        post: operations["chain_verify_v1_host_chain_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/secrets/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Secrets List */
        post: operations["secrets_list_v1_host_secrets_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/secrets/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Secrets Get */
        post: operations["secrets_get_v1_host_secrets_get_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/secrets/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Secrets Set */
        post: operations["secrets_set_v1_host_secrets_set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/secrets/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Secrets Delete */
        post: operations["secrets_delete_v1_host_secrets_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/autonomy/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autonomy Status */
        get: operations["autonomy_status_v1_host_autonomy_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/autonomy/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autonomy Start */
        post: operations["autonomy_start_v1_host_autonomy_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/autonomy/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autonomy Stop */
        post: operations["autonomy_stop_v1_host_autonomy_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AutonomyStatusResponse */
        AutonomyStatusResponse: {
            /**
             * Running
             * @default false
             */
            running: boolean;
            /**
             * In Quiet Hours
             * @default false
             */
            in_quiet_hours: boolean;
            /**
             * Ticks
             * @default 0
             */
            ticks: number;
            /**
             * Events Processed
             * @default 0
             */
            events_processed: number;
            /**
             * Goals Checked
             * @default 0
             */
            goals_checked: number;
            /**
             * Initiatives Generated
             * @default 0
             */
            initiatives_generated: number;
            /**
             * Actions Executed
             * @default 0
             */
            actions_executed: number;
            /**
             * Errors
             * @default 0
             */
            errors: number;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
        };
        /** BriefingListResponse */
        BriefingListResponse: {
            /**
             * Briefings
             * @default []
             */
            briefings: components["schemas"]["BriefingResponse"][];
        };
        /** BriefingResponse */
        BriefingResponse: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Body */
            body: string;
            /** Briefing Type */
            briefing_type?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** ChainVerifyRequest */
        ChainVerifyRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Data */
            data: string;
            /** Signature */
            signature?: string | null;
        };
        /** ChainVerifyResponse */
        ChainVerifyResponse: {
            /** Valid */
            valid: boolean;
            /** Colony Id */
            colony_id?: string | null;
        };
        /** CognitionCycleRequest */
        CognitionCycleRequest: {
            identity: components["schemas"]["HostIdentity"];
            context?: components["schemas"]["HostTurnContext"] | null;
        };
        /** CognitionCycleResponse */
        CognitionCycleResponse: {
            cpi?: components["schemas"]["CognitivePerformanceIndex"] | null;
            /**
             * Gaps
             * @default []
             */
            gaps: components["schemas"]["CognitionGap"][];
            /**
             * Adjustments
             * @default []
             */
            adjustments: {
                [key: string]: unknown;
            }[];
        };
        /** CognitionGap */
        CognitionGap: {
            /** Gap Id */
            gap_id: string;
            /** Domain */
            domain: string;
            /** Severity */
            severity: number;
            /** Description */
            description?: string | null;
        };
        /** CognitivePerformanceIndex */
        CognitivePerformanceIndex: {
            /**
             * Overall
             * @default 0
             */
            overall: number;
            /**
             * Memory
             * @default 0
             */
            memory: number;
            /**
             * Reasoning
             * @default 0
             */
            reasoning: number;
            /**
             * Social
             * @default 0
             */
            social: number;
            /**
             * Autonomy
             * @default 0
             */
            autonomy: number;
            /** Domains */
            domains?: {
                [key: string]: number;
            } | null;
        };
        /** ContactListResponse */
        ContactListResponse: {
            /**
             * Contacts
             * @default []
             */
            contacts: components["schemas"]["ContactResponse"][];
        };
        /** ContactResponse */
        ContactResponse: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Trust Tier */
            trust_tier?: string | null;
            /** Style Notes */
            style_notes?: {
                [key: string]: unknown;
            } | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** ContactStyleRequest */
        ContactStyleRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Person Id */
            person_id: string;
        };
        /** ContactStyleResponse */
        ContactStyleResponse: {
            /** Person Id */
            person_id: string;
            /** Formality */
            formality?: string | null;
            /** Tone */
            tone?: string | null;
            /** Notes */
            notes?: {
                [key: string]: unknown;
            } | null;
        };
        /** ContextAssembleRequest */
        ContextAssembleRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            incoming_message: components["schemas"]["HostMessage"];
            /** Available Tools */
            available_tools?: string[] | null;
            /** Citations Mode */
            citations_mode?: ("off" | "inline" | "appendix") | null;
        };
        /** ContextAssembleResponse */
        ContextAssembleResponse: {
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["ContextSection"][];
            /** Notices */
            notices?: string[] | null;
        };
        /** ContextSection */
        ContextSection: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Body */
            body: string;
            /** Priority */
            priority?: number | null;
            /** Citations */
            citations?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** DeliveryListResponse */
        DeliveryListResponse: {
            /**
             * Pending
             * @default []
             */
            pending: {
                [key: string]: unknown;
            }[];
        };
        /** DeliveryMarkRequest */
        DeliveryMarkRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Delivery Id */
            delivery_id: string;
        };
        /** EnrichedContextRequest */
        EnrichedContextRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            /** Message */
            message: string;
            /** Features */
            features?: {
                [key: string]: boolean;
            } | null;
        };
        /** EnrichedContextResponse */
        EnrichedContextResponse: {
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["ContextSection"][];
            /** Contact Id */
            contact_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** EntityListResponse */
        EntityListResponse: {
            /**
             * Entities
             * @default []
             */
            entities: components["schemas"]["EntityResponse"][];
        };
        /** EntityQueryRequest */
        EntityQueryRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Query */
            query: string;
            /**
             * Limit
             * @default 10
             */
            limit: number | null;
        };
        /** EntityResponse */
        EntityResponse: {
            /** Id */
            id: string;
            /** Entity Type */
            entity_type: string;
            /** Name */
            name: string;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            } | null;
        };
        /** GoalCreateRequest */
        GoalCreateRequest: {
            identity: components["schemas"]["HostIdentity"];
            context?: components["schemas"]["HostTurnContext"] | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Priority
             * @default medium
             */
            priority: string | null;
            /** Parent Goal Id */
            parent_goal_id?: string | null;
            /** Person Id */
            person_id?: string | null;
        };
        /** GoalListResponse */
        GoalListResponse: {
            /**
             * Goals
             * @default []
             */
            goals: components["schemas"]["GoalResponse"][];
        };
        /** GoalResponse */
        GoalResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /**
             * Priority
             * @default medium
             */
            priority: string;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Parent Goal Id */
            parent_goal_id?: string | null;
            /** Person Id */
            person_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** GoalUpdateRequest */
        GoalUpdateRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Status */
            status?: string | null;
            /** Progress */
            progress?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostHealthResponse */
        HostHealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "starting" | "stopping";
            /**
             * Api Version
             * @default 1.0.0
             */
            api_version: string;
            /**
             * Capabilities
             * @default []
             */
            capabilities: string[];
            /** Notes */
            notes?: {
                [key: string]: string;
            } | null;
        };
        /** HostIdentity */
        HostIdentity: {
            /** Host Id */
            host_id: string;
            /** Host Version */
            host_version?: string | null;
            /** Plugin Version */
            plugin_version?: string | null;
            /** Instance Id */
            instance_id?: string | null;
        };
        /** HostMessage */
        HostMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system" | "tool";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** HostTurnContext */
        HostTurnContext: {
            /** Session Id */
            session_id: string;
            /** Contact Id */
            contact_id: string;
            /** Channel Id */
            channel_id?: string | null;
            /** Turn Id */
            turn_id?: string | null;
            /** Locale */
            locale?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** IdentityInitRequest */
        IdentityInitRequest: {
            identity: components["schemas"]["HostIdentity"];
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** IdentityStatusResponse */
        IdentityStatusResponse: {
            /** Colony Id */
            colony_id?: string | null;
            /** Public Key */
            public_key?: string | null;
            /**
             * Initialized
             * @default false
             */
            initialized: boolean;
        };
        /** InsightResponse */
        InsightResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Insight Type */
            insight_type?: string | null;
            /**
             * Novelty
             * @default 0
             */
            novelty: number;
            /**
             * Entities
             * @default []
             */
            entities: string[];
            /** Created At */
            created_at?: string | null;
            /**
             * Dismissed
             * @default false
             */
            dismissed: boolean;
        };
        /** InsightsListResponse */
        InsightsListResponse: {
            /**
             * Insights
             * @default []
             */
            insights: components["schemas"]["InsightResponse"][];
        };
        /** LearningCorrectionRequest */
        LearningCorrectionRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            /** Original */
            original: string;
            /** Correction */
            correction: string;
            /** Component */
            component?: string | null;
        };
        /** LearningEngagementRequest */
        LearningEngagementRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Briefing Id */
            briefing_id: string;
            /** Action */
            action: string;
            /** Dwell Seconds */
            dwell_seconds?: number | null;
        };
        /** LearningWeightsResponse */
        LearningWeightsResponse: {
            /**
             * Weights
             * @default {}
             */
            weights: {
                [key: string]: number;
            };
            /**
             * Stats
             * @default {}
             */
            stats: {
                [key: string]: number;
            };
        };
        /** MemoryEmbedRequest */
        MemoryEmbedRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Inputs */
            inputs: string[];
            /** Model */
            model?: string | null;
        };
        /** MemoryEmbedResponse */
        MemoryEmbedResponse: {
            /** Model */
            model: string;
            /** Vectors */
            vectors: number[][];
        };
        /** MemoryEntry */
        MemoryEntry: {
            /** Id */
            id: string;
            /** Content */
            content: string;
            /** Type */
            type?: string | null;
            /** Strength */
            strength?: number | null;
            /** Person Id */
            person_id?: string | null;
            /** Entities */
            entities?: string[] | null;
            /** Tags */
            tags?: string[] | null;
            /** Created At */
            created_at?: string | null;
            /** Score */
            score?: number | null;
        };
        /** MemoryFlushRequest */
        MemoryFlushRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Reason */
            reason?: string | null;
        };
        /** MemoryFlushResponse */
        MemoryFlushResponse: {
            /** Accepted */
            accepted: boolean;
            /** Job Id */
            job_id?: string | null;
        };
        /** MemoryReadRequest */
        MemoryReadRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Memory Id */
            memory_id?: string | null;
            /** Person Id */
            person_id?: string | null;
            /** Limit */
            limit?: number | null;
        };
        /** MemoryReadResponse */
        MemoryReadResponse: {
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["MemoryEntry"][];
        };
        /** MemorySearchRequest */
        MemorySearchRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Query */
            query: string;
            /** Limit */
            limit?: number | null;
            /** Min Score */
            min_score?: number | null;
            /** Person Id */
            person_id?: string | null;
            /** Types */
            types?: string[] | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** MemorySearchResponse */
        MemorySearchResponse: {
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["MemoryEntry"][];
        };
        /** MemoryWriteRequest */
        MemoryWriteRequest: {
            identity: components["schemas"]["HostIdentity"];
            context?: components["schemas"]["HostTurnContext"] | null;
            /** Content */
            content: string;
            /** Type */
            type?: string | null;
            /** Person Id */
            person_id?: string | null;
            /** Entities */
            entities?: string[] | null;
            /** Tags */
            tags?: string[] | null;
            /** Strength */
            strength?: number | null;
        };
        /** MemoryWriteResponse */
        MemoryWriteResponse: {
            /** Id */
            id: string;
            /** Accepted */
            accepted: boolean;
        };
        /** ReasoningToolCall */
        ReasoningToolCall: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
        };
        /** ReasoningTurnRequest */
        ReasoningTurnRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            /** Messages */
            messages: components["schemas"]["HostMessage"][];
            /** Available Tools */
            available_tools?: string[];
            /** Model Override */
            model_override?: string | null;
        };
        /** ReasoningTurnResponse */
        ReasoningTurnResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "needs_tool" | "error";
            message?: components["schemas"]["HostMessage"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ReasoningToolCall"][];
            /** Usage */
            usage?: {
                [key: string]: unknown;
            };
            /** Error */
            error?: string | null;
        };
        /** ResearchListResponse */
        ResearchListResponse: {
            /**
             * Runs
             * @default []
             */
            runs: components["schemas"]["ResearchRunResponse"][];
        };
        /** ResearchRunResponse */
        ResearchRunResponse: {
            /** Run Id */
            run_id: string;
            /** Topic */
            topic: string;
            /** Status */
            status: string;
            /**
             * Stages Completed
             * @default []
             */
            stages_completed: string[];
            /** Artifact */
            artifact?: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at?: string | null;
        };
        /** ResearchStartRequest */
        ResearchStartRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Topic */
            topic: string;
            /**
             * Depth
             * @default standard
             */
            depth: string | null;
            /** Person Id */
            person_id?: string | null;
        };
        /** SafetyCheckRequest */
        SafetyCheckRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            /** Response Text */
            response_text: string;
            /** Incoming Message Text */
            incoming_message_text?: string | null;
            /** Target Gateway */
            target_gateway?: string | null;
            /** Trust Tier */
            trust_tier?: string | null;
            /** Mentioned Entities */
            mentioned_entities?: string[] | null;
        };
        /** SafetyCheckResponse */
        SafetyCheckResponse: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "pass" | "block" | "pending";
            /** Blocked */
            blocked: boolean;
            /** Blocking Layer */
            blocking_layer?: number | null;
            /** Reason */
            reason?: string | null;
            /** Flagged Excerpt */
            flagged_excerpt?: string | null;
            /** Layer Results */
            layer_results?: {
                [key: string]: unknown;
            } | null;
        };
        /** SecretDeleteRequest */
        SecretDeleteRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Key */
            key: string;
        };
        /** SecretDeleteResponse */
        SecretDeleteResponse: {
            /** Key */
            key: string;
            /** Deleted */
            deleted: boolean;
        };
        /** SecretGetRequest */
        SecretGetRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Key */
            key: string;
        };
        /** SecretGetResponse */
        SecretGetResponse: {
            /** Key */
            key: string;
            /** Value */
            value?: string | null;
            /**
             * Exists
             * @default false
             */
            exists: boolean;
        };
        /** SecretListRequest */
        SecretListRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Prefix */
            prefix?: string | null;
        };
        /** SecretListResponse */
        SecretListResponse: {
            /**
             * Keys
             * @default []
             */
            keys: string[];
        };
        /** SecretSetRequest */
        SecretSetRequest: {
            identity: components["schemas"]["HostIdentity"];
            /** Key */
            key: string;
            /** Value */
            value: string;
            /** Secret Type */
            secret_type?: string | null;
        };
        /** SecretSetResponse */
        SecretSetResponse: {
            /** Key */
            key: string;
            /** Stored */
            stored: boolean;
        };
        /** SignalIngestRequest */
        SignalIngestRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            incoming_message?: components["schemas"]["HostMessage"] | null;
            outgoing_message?: components["schemas"]["HostMessage"] | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ReasoningToolCall"][];
            /** Correction */
            correction?: string | null;
        };
        /** SignalIngestResponse */
        SignalIngestResponse: {
            /** Accepted */
            accepted: boolean;
            /** Signals Recorded */
            signals_recorded: number;
        };
        /** SkillDetailResponse */
        SkillDetailResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Version */
            version?: string | null;
            /**
             * Triggers
             * @default []
             */
            triggers: string[];
            /** Input Schema */
            input_schema?: {
                [key: string]: unknown;
            } | null;
            /** Permissions */
            permissions?: {
                [key: string]: unknown;
            } | null;
        };
        /** SkillSummary */
        SkillSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Version */
            version?: string | null;
            /**
             * Triggers
             * @default []
             */
            triggers: string[];
        };
        /** SkillsListResponse */
        SkillsListResponse: {
            /**
             * Skills
             * @default []
             */
            skills: components["schemas"]["SkillSummary"][];
        };
        /** SynthesisConnection */
        SynthesisConnection: {
            /** Id */
            id: string;
            /** Connection Type */
            connection_type: string;
            /**
             * Entities
             * @default []
             */
            entities: string[];
            /**
             * Novelty
             * @default 0
             */
            novelty: number;
            /** Description */
            description?: string | null;
        };
        /** SynthesisDiscoverRequest */
        SynthesisDiscoverRequest: {
            identity: components["schemas"]["HostIdentity"];
            context?: components["schemas"]["HostTurnContext"] | null;
            /** Person Id */
            person_id?: string | null;
            /**
             * Min Novelty
             * @default 0.3
             */
            min_novelty: number | null;
        };
        /** SynthesisDiscoverResponse */
        SynthesisDiscoverResponse: {
            /**
             * Connections
             * @default []
             */
            connections: components["schemas"]["SynthesisConnection"][];
        };
        /** TurnSyncRequest */
        TurnSyncRequest: {
            identity: components["schemas"]["HostIdentity"];
            context: components["schemas"]["HostTurnContext"];
            /** Topics */
            topics?: string[];
            /** Entities */
            entities?: string[];
            /** Pending Tasks */
            pending_tasks?: string[];
            /** Tools Used */
            tools_used?: string[];
            /** Summary */
            summary?: string | null;
        };
        /** TurnSyncResponse */
        TurnSyncResponse: {
            /** Accepted */
            accepted: boolean;
            /** Continuity Updated */
            continuity_updated: boolean;
            /** Skipped Reason */
            skipped_reason?: string | null;
            /** Errors */
            errors?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_host_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostHealthResponse"];
                };
            };
        };
    };
    memory_read_v1_host_memory_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryReadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_write_v1_host_memory_write_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryWriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_search_v1_host_memory_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemorySearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemorySearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_flush_v1_host_memory_flush_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryFlushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryFlushResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_embed_v1_host_memory_embed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryEmbedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEmbedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    context_assemble_v1_host_context_assemble_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextAssembleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextAssembleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reasoning_turn_v1_host_reasoning_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasoningTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReasoningTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signals_ingest_v1_host_signals_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turns_sync_v1_host_turns_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    safety_check_v1_host_safety_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafetyCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_v1_host_goals_get: {
        parameters: {
            query?: {
                person_id?: string | null;
                status_filter?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_goal_v1_host_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_v1_host_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_goal_v1_host_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contacts_v1_host_contacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactListResponse"];
                };
            };
        };
    };
    get_contact_v1_host_contacts__contact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contact_style_v1_host_contacts__contact_id__style_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactStyleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactStyleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_briefings_v1_host_briefings_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_entities_v1_host_world_entities_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_v1_host_world_entities_get: {
        parameters: {
            query?: {
                entity_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cognition_cycle_v1_host_cognition_cycle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CognitionCycleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CognitionCycleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cpi_v1_host_cognition_cpi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CognitivePerformanceIndex"];
                };
            };
        };
    };
    start_research_v1_host_research_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_v1_host_research_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_deliveries_v1_host_delivery_pending_get: {
        parameters: {
            query?: {
                gateway_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_delivery_sent_v1_host_delivery_mark_sent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryMarkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_connections_v1_host_synthesis_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SynthesisDiscoverRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SynthesisDiscoverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_correction_v1_host_learning_correction_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_engagement_v1_host_learning_engagement_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningEngagementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_learning_weights_v1_host_learning_weights_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningWeightsResponse"];
                };
            };
        };
    };
    list_skills_v1_host_skills_registry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsListResponse"];
                };
            };
        };
    };
    get_skill_v1_host_skills_registry__skill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_insights_v1_host_insights_get: {
        parameters: {
            query?: {
                limit?: number;
                dismissed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_insight_v1_host_insights__insight_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                insight_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enriched_context_v1_host_context_enriched_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichedContextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichedContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    identity_status_v1_host_identity_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityStatusResponse"];
                };
            };
        };
    };
    identity_init_v1_host_identity_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityInitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chain_verify_v1_host_chain_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChainVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    secrets_list_v1_host_secrets_list_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretListRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    secrets_get_v1_host_secrets_get_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretGetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretGetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    secrets_set_v1_host_secrets_set_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretSetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    secrets_delete_v1_host_secrets_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autonomy_status_v1_host_autonomy_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutonomyStatusResponse"];
                };
            };
        };
    };
    autonomy_start_v1_host_autonomy_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutonomyStatusResponse"];
                };
            };
        };
    };
    autonomy_stop_v1_host_autonomy_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutonomyStatusResponse"];
                };
            };
        };
    };
}
